name: vatic
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=5.1
  - appdirs=1.4.4
  - asttokens=2.0.5
  - attrs=21.4.0
  - aws-c-common=0.4.57
  - aws-c-event-stream=0.1.6
  - aws-checksums=0.1.9
  - aws-sdk-cpp=1.8.185
  - backcall=0.2.0
  - blas=1.0
  - bottleneck=1.3.5
  - brotli=1.0.9
  - brotli-bin=1.0.9
  - bzip2=1.0.8
  - c-ares=1.18.1
  - ca-certificates=2022.6.15
  - cairo=1.16.0
  - certifi=2022.6.15
  - cfitsio=3.470
  - click=7.1.2
  - click-plugins=1.1.1
  - cligj=0.7.2
  - curl=7.82.0
  - cycler=0.11.0
  - dbus=1.13.18
  - debugpy=1.5.1
  - decorator=5.1.1
  - dill=0.3.4
  - entrypoints=0.4
  - executing=0.8.3
  - expat=2.4.4
  - fiona=1.8.13.post1
  - fontconfig=2.13.1
  - fonttools=4.25.0
  - freetype=2.11.0
  - freexl=1.0.6
  - gdal=3.0.2
  - geopandas=0.9.0
  - geopandas-base=0.9.0
  - geos=3.8.0
  - geotiff=1.7.0
  - giflib=5.2.1
  - glib=2.69.1
  - gst-plugins-base=1.14.0
  - gstreamer=1.14.0
  - hdf4=4.2.13
  - hdf5=1.10.6
  - icu=58.2
  - imageio=2.9.0
  - intel-openmp=2021.4.0
  - ipykernel=6.9.1
  - ipython=8.4.0
  - jedi=0.18.1
  - joblib=1.1.0
  - jpeg=9e
  - json-c=0.13.1
  - jupyter_client=7.2.2
  - jupyter_core=4.10.0
  - kealib=1.4.14
  - kiwisolver=1.4.2
  - krb5=1.19.2
  - lcms2=2.12
  - ld_impl_linux-64=2.38
  - libblas=3.9.0
  - libboost=1.73.0
  - libbrotlicommon=1.0.9
  - libbrotlidec=1.0.9
  - libbrotlienc=1.0.9
  - libcblas=3.9.0
  - libcurl=7.82.0
  - libdap4=3.19.1
  - libedit=3.1.20210910
  - libev=4.33
  - libffi=3.3
  - libgcc-ng=11.2.0
  - libgdal=3.0.2
  - libgfortran-ng=7.5.0
  - libgfortran4=7.5.0
  - libgomp=11.2.0
  - libkml=1.3.0
  - liblapack=3.9.0
  - libnetcdf=4.8.1
  - libnghttp2=1.46.0
  - libopenblas=0.3.18
  - libpng=1.6.37
  - libpq=12.9
  - libsodium=1.0.18
  - libspatialindex=1.9.3
  - libspatialite=4.3.0a
  - libssh2=1.10.0
  - libstdcxx-ng=11.2.0
  - libtiff=4.2.0
  - libuuid=1.0.3
  - libwebp=1.2.2
  - libwebp-base=1.2.2
  - libxcb=1.15
  - libxml2=2.9.14
  - libzip=1.5.1
  - llvm-openmp=12.0.1
  - lz4-c=1.9.3
  - mapclassify=2.4.3
  - matplotlib=3.5.1
  - matplotlib-base=3.5.1
  - matplotlib-inline=0.1.2
  - memory_profiler=0.60.0
  - mkl=2021.4.0
  - mkl-service=2.4.0
  - mkl_fft=1.3.1
  - mkl_random=1.2.2
  - munch=2.5.0
  - munkres=1.1.4
  - ncurses=6.3
  - nest-asyncio=1.5.5
  - networkx=2.8.4
  - nose=1.3.7
  - numexpr=2.8.1
  - numpy=1.22.3
  - numpy-base=1.22.3
  - olefile=0.46
  - openjpeg=2.4.0
  - openssl=1.1.1q
  - packaging=21.3
  - pandas=1.4.3
  - parso=0.8.3
  - patsy=0.5.2
  - pcre=8.45
  - pexpect=4.8.0
  - pickleshare=0.7.5
  - pillow=9.2.0
  - pip==22.1.2
  - pixman=0.40.0
  - ply=3.11
  - poppler=0.81.0
  - poppler-data=0.4.11
  - proj=6.2.1
  - prompt-toolkit=3.0.20
  - psutil=5.9.1
  - pthread-stubs=0.4
  - ptyprocess=0.7.0
  - pure_eval=0.2.2
  - pygments=2.11.2
  - pyomo=6.4.0
  - pyparsing=3.0.4
  - pyproj=2.6.1.post1
  - pyqt=5.9.2
  - python=3.8.13
  - python-dateutil=2.8.2
  - python_abi=3.8
  - pytz=2022.1
  - pyutilib=6.0.0
  - pyzmq=23.2.0
  - qt=5.9.7
  - readline=8.1.2
  - rtree=0.9.7
  - scikit-learn=1.1.1
  - scipy=1.7.3
  - shapely=1.7.1
  - sip=4.19.13
  - six=1.16.0
  - sqlite=3.38.5
  - stack_data=0.2.0
  - statsmodels=0.13.2
  - threadpoolctl=2.2.0
  - tiledb=2.2.9
  - tk=8.6.12
  - tornado=6.1
  - traitlets=5.1.1
  - unicodedata2=14.0.0
  - wcwidth=0.2.5
  - wheel=0.37.1
  - xerces-c=3.2.3
  - xorg-libxau=1.0.9
  - xorg-libxdmcp=1.1.3
  - xz=5.2.5
  - zeromq=4.3.4
  - zlib=1.2.12
  - zstd=1.4.9
  - pip:
    - gurobipy==10.0.1
    - ordered-set==4.1.0
    - iniconfig==1.1.1
    - pluggy==1.0.0
    - py==1.11.0
    - pytest==7.1.1
    - seaborn==0.11.2
    - setuptools==63.2.0
    - tomli==2.0.1
