name: CI-test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-20.04, ubuntu-18.04, macos-11, macos-10.15]

    steps:
      - uses: actions/checkout@v3

      - uses: conda-incubator/setup-miniconda@v2
        with:
          auto-update-conda: true
          auto-activate-base: true
          python-version: 3.8

      - name: test-run
        shell: bash -l {0}
        run: |
          cd $GITHUB_WORKSPACE
          pip install .
          conda install -c conda-forge coincbc
          tree /usr/share/miniconda/envs/test/lib/python3.8/site-packages/vatic
          sh vatic/tests/check_rts.sh
          echo tests finished successfully!

