name: CI-test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-11]

    steps:
      - uses: actions/checkout@v3

      - uses: conda-incubator/setup-miniconda@v2
        with:
          auto-update-conda: true
          python-version: 3.8

      - name: test-run
        shell: bash -l {0}
        run: |
          cd $GITHUB_WORKSPACE
          git submodule update --init

          conda create --name vatic --file vatic/tests/spec-file_mac-os.txt
          conda activate vatic
          pip install .

          sh vatic/tests/check_rts.sh
          echo tests finished successfully!

